In [3]:
np.random.seed(0)
sale_amount=np.random.randint(20,size=(5,3))
sale_amount

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [6]:
weekly_sales=pd.DataFrame(sale_amount,index=["mon","tues","wed","thurs","fri"],columns=["Almund butter","Peanut butter","Cashew Butter"])

<IPython.core.display.Javascript object>

In [7]:
weekly_sales

Almund butter  Peanut butter  Cashew Butter
mon               12             15              0
tues               3              3              7
wed                9             19             18
thurs              4              6             12
fri                1              6              7

In [8]:
princs=np.array([10,8,12])
princs

<IPython.core.display.Javascript object>

array([10,  8, 12])

In [11]:
princs.shape


(3,)

In [13]:
better_price=pd.DataFrame(princs.reshape(1,3),index=["price"],columns=["Almund butter","Peanut butter","Cashew Butter"])

<IPython.core.display.Javascript object>

In [14]:
better_price

Almund butter  Peanut butter  Cashew Butter
price             10              8             12

In [16]:
total_price=princs.dot(sale_amount.T)

In [17]:
total_price

array([240, 138, 458, 232, 142])

In [18]:
weekly_sales["total price"]=total_price

In [19]:
weekly_sales

Almund butter  Peanut butter  Cashew Butter  total price
mon               12             15              0          240
tues               3              3              7          138
wed                9             19             18          458
thurs              4              6             12          232
fri                1              6              7          142